#!/usr/bin/env bash
# ───────────────────────────────────────────────────────────
# build-wp.sh — Generate wordpress/jetlag-wpcode.html
#
# Reads the shared source files (css/core.css, js/*.js) and
# assembles them into a single self-contained HTML snippet
# that can be pasted into WPCode as a "Shortcode" snippet.
#
# Usage:  ./wordpress/build-wp.sh        (from project root)
#     or: cd wordpress && ./build-wp.sh
# ───────────────────────────────────────────────────────────
set -euo pipefail

# Resolve project root (works whether called from project root or wordpress/)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$SCRIPT_DIR/jetlag-wpcode.html"

echo "Building $OUT from source files..."

# ── Collect source files ──────────────────────────────────
CORE_CSS="$ROOT/css/core.css"
TZ_JS="$ROOT/js/timezones.js"
ALG_JS="$ROOT/js/jet-lag-algorithm.js"
APP_JS="$ROOT/js/app.js"

for f in "$CORE_CSS" "$TZ_JS" "$ALG_JS" "$APP_JS"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Missing source file: $f" >&2
        exit 1
    fi
done

# ── Extract HTML fragment from index.html ─────────────────
# We grab the sections inside <main> and the <template>, skipping header/footer.
# This avoids duplicating HTML in a separate file.
INDEX="$ROOT/index.html"

# Extract content between <main> and </main>
MAIN_HTML=$(sed -n '/<main>/,/<\/main>/p' "$INDEX" | sed '1d;$d')

# Extract the <template> block
TEMPLATE_HTML=$(sed -n '/<template id="flight-template">/,/<\/template>/p' "$INDEX")

# ── Write the HTML file ───────────────────────────────────
cat > "$OUT" << 'HEADER'
<!--
  JetLag Planner — WordPress Embed via WPCode

  AUTO-GENERATED by wordpress/build-wp.sh — do not edit by hand.
  To update, modify the source files and re-run the build script.

  SETUP:
    1. Install WPCode plugin
    2. Create a new snippet — set Code Type to "HTML Snippet"
    3. Paste this entire file's contents into the code box
    4. Under Insertion, select "Shortcode" and note the shortcode
       (e.g. [wpcode id="123"])
    5. Activate the snippet and add the shortcode to any page or post

  DARK MODE:
    By default the planner adapts to your theme's colors.
    To force the original dark appearance, change the line below from
        <div class="jetlag-planner">
    to
        <div class="jetlag-planner jetlag-planner--dark">
-->
HEADER

# ── Inline CSS ────────────────────────────────────────────
echo '<style>' >> "$OUT"
cat "$CORE_CSS" >> "$OUT"
cat >> "$OUT" << 'WPCSS'

/* WordPress-specific: suppress body-level flex layout */
.jetlag-planner .app-container {
    display: block;
}
WPCSS
echo '</style>' >> "$OUT"

# ── HTML ──────────────────────────────────────────────────
printf '\n<div class="jetlag-planner">\n' >> "$OUT"
printf '    <div class="app-container">\n' >> "$OUT"

echo "$MAIN_HTML" >> "$OUT"

printf '    </div>\n\n' >> "$OUT"

echo "$TEMPLATE_HTML" >> "$OUT"

printf '</div>\n\n' >> "$OUT"

# ── Inline JS (IIFE) ─────────────────────────────────────
echo '<script>' >> "$OUT"
echo '(function() {' >> "$OUT"
echo '"use strict";' >> "$OUT"
echo '' >> "$OUT"

# timezones.js (data + helpers)
cat "$TZ_JS" >> "$OUT"
echo '' >> "$OUT"

# jet-lag-algorithm.js (pure logic)
cat "$ALG_JS" >> "$OUT"
echo '' >> "$OUT"

# app.js (UI logic — auto-init at bottom will fire via DOMContentLoaded)
cat "$APP_JS" >> "$OUT"
echo '' >> "$OUT"

echo '})();' >> "$OUT"
echo '</script>' >> "$OUT"

echo "Done. Output: $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
