#!/usr/bin/env bash
# ───────────────────────────────────────────────────────────
# build-wp.sh — Generate wordpress/jetlag-wpcode.php
#
# Reads the shared source files (css/core.css, js/*.js) and
# assembles them into a single self-contained PHP snippet
# that can be pasted into WPCode.
#
# Usage:  ./wordpress/build-wp.sh        (from project root)
#     or: cd wordpress && ./build-wp.sh
# ───────────────────────────────────────────────────────────
set -euo pipefail

# Resolve project root (works whether called from project root or wordpress/)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$SCRIPT_DIR/jetlag-wpcode.php"

echo "Building $OUT from source files..."

# ── Collect source files ──────────────────────────────────
CORE_CSS="$ROOT/css/core.css"
TZ_JS="$ROOT/js/timezones.js"
ALG_JS="$ROOT/js/jet-lag-algorithm.js"
APP_JS="$ROOT/js/app.js"

for f in "$CORE_CSS" "$TZ_JS" "$ALG_JS" "$APP_JS"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Missing source file: $f" >&2
        exit 1
    fi
done

# ── Extract HTML fragment from index.html ─────────────────
# We grab the sections inside <main> and the <template>, skipping header/footer.
# This avoids duplicating HTML in a separate file.
INDEX="$ROOT/index.html"

# Extract content between <main> and </main>
MAIN_HTML=$(sed -n '/<main>/,/<\/main>/p' "$INDEX" | sed '1d;$d')

# Extract the <template> block
TEMPLATE_HTML=$(sed -n '/<template id="flight-template">/,/<\/template>/p' "$INDEX")

# ── Write the PHP file ────────────────────────────────────
cat > "$OUT" << 'PHPHEADER'
<?php
/**
 * JetLag Planner — WordPress Embed via WPCode
 *
 * AUTO-GENERATED by wordpress/build-wp.sh — do not edit by hand.
 * To update, modify the source files and re-run the build script.
 *
 * SETUP:
 *   1. Install WPCode plugin (or paste into theme's functions.php)
 *   2. Create a new "PHP Snippet" in WPCode
 *   3. Paste this entire file's contents
 *   4. Activate the snippet
 *   5. Add [jetlag_planner] to any page or post
 *
 * OPTIONS:
 *   [jetlag_planner]              — theme-adaptive (inherits your theme's style)
 *   [jetlag_planner dark="true"]  — original dark mode appearance
 */

if ( ! function_exists( 'jetlag_planner_shortcode' ) ) {

    add_shortcode( 'jetlag_planner', 'jetlag_planner_shortcode' );

    function jetlag_planner_shortcode( $atts ) {
        $atts = shortcode_atts( array( 'dark' => '' ), $atts, 'jetlag_planner' );
        $dark = filter_var( $atts['dark'], FILTER_VALIDATE_BOOLEAN );
        $cls  = 'jetlag-planner' . ( $dark ? ' jetlag-planner--dark' : '' );

        ob_start();
?>
PHPHEADER

# ── Inline CSS ────────────────────────────────────────────
echo '<style>' >> "$OUT"
cat "$CORE_CSS" >> "$OUT"
cat >> "$OUT" << 'WPCSS'

/* WordPress-specific: suppress body-level flex layout */
.jetlag-planner .app-container {
    display: block;
}
WPCSS
echo '</style>' >> "$OUT"

# ── HTML ──────────────────────────────────────────────────
printf '\n<div class="<?php echo esc_attr( $cls ); ?>">\n' >> "$OUT"
printf '    <div class="app-container">\n' >> "$OUT"

echo "$MAIN_HTML" >> "$OUT"

printf '    </div>\n\n' >> "$OUT"

echo "$TEMPLATE_HTML" >> "$OUT"

printf '</div>\n\n' >> "$OUT"

# ── Inline JS (IIFE) ─────────────────────────────────────
echo '<script>' >> "$OUT"
echo '(function() {' >> "$OUT"
echo '"use strict";' >> "$OUT"
echo '' >> "$OUT"

# timezones.js (data + helpers)
cat "$TZ_JS" >> "$OUT"
echo '' >> "$OUT"

# jet-lag-algorithm.js (pure logic)
cat "$ALG_JS" >> "$OUT"
echo '' >> "$OUT"

# app.js (UI logic — auto-init at bottom will fire via DOMContentLoaded)
cat "$APP_JS" >> "$OUT"
echo '' >> "$OUT"

echo '})();' >> "$OUT"
echo '</script>' >> "$OUT"

# ── Close PHP ─────────────────────────────────────────────
cat >> "$OUT" << 'PHPFOOTER'
<?php
        return ob_get_clean();
    }
}
PHPFOOTER

echo "Done. Output: $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
